### PR TITLE
modify Vagrantfile with repartition the disk

### PR DESCRIPTION
**Pull request by ianamunoz**
This corrects the automatic repartition. Albeit a little bit ugly due to bugs in parted and this particular release of debian.

### CODE REVIEW

**Comment by charlieok** [comment]
Tested ACK 👍

**Comment by bitcartel** [comment]
Did you also run the gitian build script?  Since the swap partition is removed, curious to know if the build completed okay or ran out of memory since the Vagrantfile only allocates 4 GB of ram.  Also I usually tweak my settings to allocate 4 or 8 cores which will probably increase the memory requirements.  Are you able to create a swap partition?

**Comment by charlieok** [comment]
I'm still trying to go through the complete gitian build instructions, but in my case I believe the build did complete without running out of memory. In this case my tested ack above means it got past the "out of disk space" error.

**Comment by ianamunoz** [comment]
I'll profile the build and see if there is resource pressure.

**Comment by bitcartel** [comment]
Closing this PR as superceded by #21 which was merged.

**Pull request closed without merging**
