### PR TITLE
update to stretch for gitian builds

### PR DESCRIPTION
**Pull request by ianamunoz**
This PR updates zcash-gitian to Stretch so that it completes successfully in a reproducible manner.

### CODE REVIEW

**Comment by charlieok** [comment]
I think some of the references here refer to the OS used inside the LXC container.

Maybe that's what we want, but in that case it should be synced with an update to this field in the zcash repo:
https://github.com/zcash/zcash/blob/59e82c64e94504036239a994424bb88d72c4434a/contrib/gitian-descriptors/gitian-linux.yml#L6

**Comment by ianamunoz** [comment]
Yep. See: https://github.com/zcash/zcash/pull/3914

**Comment by charlieok** [comment]
This PR would also address https://github.com/zcash/zcash-gitian/issues/56

**Comment by charlieok** [comment]
Ack

**Comment by ianamunoz** [comment]
I think we are going to hold off on the LXC container for a release till we can assure that debian 9 will be our officially supported debian distribution.

**Comment by str4d** [comment]
Debian 9 has been officially supported for [over a year](https://github.com/Electric-Coin-Company/infrastructure/commit/a8c5cdf857415460dff10b4af95f05d326199717). The question should probably be whether Debian 8 will become unsupported, which AIUI doesn't affect this PR, because none of our CI builders go through the Gitian process. If we did add Gitian builders to CI, I'd expect that we'd have separate builders testing the available packages against supported platforms, but having no official packages for Debian 8 doesn't necessarily mean it won't be supported (availability of installers hasn't thus far been an explicit requirement for being officially supported).

**Pull request closed without merging**
